-- project euler  Problem 2

{--
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.
--}
--fibonacci sequence.. in reverse order
genFib end list
    | (head list) > end = list
    | otherwise = genFib end $ (head list) + (head $ tail list) : list

main::IO()
main = do
    print $ sum $ filter (not.odd) (genFib 4000000 [2,1])
