--project euler problem 45
{--
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle        T_(n)=n(n+1)/2      1, 3, 6, 10, 15, ...
Pentagonal      P_(n)=n(3n−1)/2         1, 5, 12, 22, 35, ...
Hexagonal       H_(n)=n(2n−1)       1, 6, 15, 28, 45, ...

It can be verified that T_(285) = P_(165) = H_(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
--}

--all triangle numbers are hexagonals as well
pentagonals = [n*(3*n-1) `div` 2 | n<-[1..]::[Integer]]
hexagonals = [n*(2*n-1) | n<-[1..]::[Integer]]

sorted_inter xx@(x:xs) yy@(y:ys)
    | x == y = x : sorted_inter xs ys
    | x > y = sorted_inter xx ys
    | x < y = sorted_inter xs yy

main = print $ head $ dropWhile (<=40755) $ sorted_inter hexagonals pentagonals

--could have also done by supplying isHex filter
--main = print $ head $ dropWhile(<=40755) $ filter isHex pentagonals
